### ISSUE TITLE
ocelot version doesn't need to make remote calls 

### ISSUE THREAD

**Issue by tjtelan** [orbitalci/orbital#124]
Unclear if this is a platform-specific (Windows) bug, but during troubleshooting with v0.7.3, we noticed that a Windows ocelot client (that was already having trouble connecting to an admin) would also fail to return `ocelot version`. This remote call doesn't need to happen to return the version number of the client.

**Comment by shankj3** [comment]
while we are rooting around in here, we might as well have it look like the `kubectl version`, where first it prints the version on the command line, then it tries to connect to the admin svc and print that  version
