### ISSUE TITLE
Need to create a homebrew-ocelot tap in level11consulting repo for the Ocelot CLI tool

### ISSUE THREAD

**Issue by eccramer** [orbitalci/orbital#156]
Was going through the installation directions for Ocelot, and found that I couldn't install the ocelot cli tools with `brew tap level11consulting/ocelot`, as there is no homebrew-ocelot repo in the level11consulting organization.

Looks like we need to fork that repo from the previous owner, or just create a new one.

Whatever the solution, the directions at https://github.com/level11consulting/ocelot/wiki/client#installation are broken.

Related to #53

**Comment by eccramer** [comment]
Creating taps is documented here: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

The homebrew-ocelot tap in shankj3's user looks to be in good shape, just needs some find/replace and to be copied under level11consulting.

**Comment by tjtelan** [comment]
Shelving this for now as there isn't a plan in the roadmap for distribution this year and I won't have time to pay attention to it.
