### ISSUE TITLE
Ocelot configuration graceful reload

### ISSUE THREAD

**Issue by tjtelan** [orbitalci/orbital#176]
I feel the need for this greatly while I have vagrant ocelot configured to use vault's (currently broken) database backend.

After changing the value for the setting, I only have the option to hard restart each component. 

A live reload (like, with envconsul, or adding logic for looking at consul for changes) would be a step in the direction I'm thinking of.

This could probably suffice with instructions for using envconsul?

**Comment by shankj3** [comment]
I think instructions may be enough if we also include it in the helm deployment / ansible deployment of all the components

**Comment by tjtelan** [comment]
Configuring a Consul agent to use the Watches feature might be another way to approach this that would be friendly in a production environment. That might allow us to keep logs of when the Ocelot configuration has been changed during runtime. https://www.consul.io/docs/agent/watches.html

Instead of an automatic reload, we could do something like add in an endpoint that will reload config from Consul, or even restart services (something that will cause configs to get re-set from Consul's kv). Then we can configure an event on our Consul agents to watch the Ocelot KV and send a request on that new Ocelot endpoint whenever a change occurs.

**Comment by tjtelan** [comment]
Closing since this is part of the legacy codebase.
