### ISSUE TITLE
release automation

### ISSUE THREAD

**Issue by shankj3** [orbitalci/orbital#62]
set up github [webhook for releases](https://developer.github.com/webhooks/) for this project

It should: 
- build all clients / worker binaries and upload to release 
- build all docker images and push to docker hub 
- update `homebrew-ocelot` repo with latest release

**Comment by tjtelan** [comment]
Closing since we're not in a position to retool the release pipeline anymore. In the future I'd like to have a pipeline where Orbital is building and releasing Orbital from this github codebase.
