### ISSUE TITLE
ocelot creds list

### ISSUE THREAD

**Issue by shankj3** [orbitalci/orbital#73]
bring back `ocelot creds list` w/ filter for account so you can see all the credentials related to your account

**Comment by eccramer** [comment]
I'm taking this issue. Notes so far:

* Ocelot doesn't really have the concept of a user or account outside of repo/account pairs.
* Probably will provide this functionality where `ocelot creds list` prints all credentials, and `ocelot creds list --acct-name <account name>` filters.

**Comment by eccramer** [comment]
Looks like `storage/postgres.go -> RetrieveCredBySubTypeAndAcct` will do what we want.

**Comment by eccramer** [comment]
Actually, it looks like we'll have to add other credential types to `router/admin/creds.go -> GetAllCreds`

**Comment by eccramer** [comment]
Update on Progress:

* Added Apple, k8s, notification, and SSH cred types to the `AllCredsWrapper` type in `models/creds/credslist.go`
* Added logic to `router/admin/creds.go -> GetAllCreds` to fetch and return aforementioned cred types in the `AllCredsWrapper`
* Added logic in `client/creds/credslist.go -> Run()` to print them.

Now I've determined that the different functions used by `GetAllCreds` to get the credentials have different expectations of what is returned. Some return `nil` if no creds were found. Some return protobuf's `empty.Empty{}`, which if the same pattern is used to print them, results in nil pointer derefs and segfaults the client.

So now I'm trying to standardize the interface between all of the `Get<Type>Creds` functions to match the `GetRepoCreds` function.
